[package]
name = "tenxrust"
version = "0.1.0"
authors = ["Richard van Roy <info@hjortronic.io>"]

[dependencies]
serde = "1.0.19"
serde_derive = "1.0.19"
bincode = "0.9.2"
sha2 = "^0.6.0"
rand = "^0.3.18"
ed25519-dalek = "^0.4.2"
